config/routes.rb
Rails.application.routes.draw do

  resources :dy_contents
  resources :dyn_images
  resources :dynamic_pages
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'membership', to: 'static_pages#membership'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get 'classes', to: 'static_pages#classes'

  get 'contact', to: 'static_pages#contact'
  
  get 'admin', to: 'static_pages#admin'
  
  get 'pages', to: 'dynamic_pages#index'
  
  get 'images', to: 'dyn_images#index'
  
  get 'contents', to: 'dy_contents#index'
  
   root 'static_pages#home'
  
 

  
end

app/models/dyn_image.rb
class DynImage < ApplicationRecord
  validates :name, :alttext, :caption, :image, :pagename, presence: true
  has_attached_file :image, :styles => { :large => "60x60%>", :medium => "40x40%>", :thumb => "150x150#" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/dyn_images_controller.rb
class DynImagesController < ApplicationController
  before_action :set_dyn_image, only: [:show, :edit, :update, :destroy]

  # GET /dyn_images
  # GET /dyn_images.json
  def index
    if params[:pagename]
      @dynamic_pages = DynamicPage.where name: params[:pagename]
      @dyn_images = DynImage.where pagename: params[:pagename];
    else
      @dynamic_pages = DynamicPage.all;
      @dyn_images = DynImage.all
    end
  end

  # GET /dyn_images/1
  # GET /dyn_images/1.json
  def show
  end

  # GET /dyn_images/new
  def new
    @dyn_image = DynImage.new
  end

  # GET /dyn_images/1/edit
  def edit
  end

  # POST /dyn_images
  # POST /dyn_images.json
  def create
    @dyn_image = DynImage.new(dyn_image_params)

    respond_to do |format|
      if @dyn_image.save
        format.html { redirect_to @dyn_image, notice: 'Dyn image was successfully created.' }
        format.json { render :show, status: :created, location: @dyn_image }
      else
        format.html { render :new }
        format.json { render json: @dyn_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dyn_images/1
  # PATCH/PUT /dyn_images/1.json
  def update
    respond_to do |format|
      if @dyn_image.update(dyn_image_params)
        format.html { redirect_to @dyn_image, notice: 'Dyn image was successfully updated.' }
        format.json { render :show, status: :ok, location: @dyn_image }
      else
        format.html { render :edit }
        format.json { render json: @dyn_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dyn_images/1
  # DELETE /dyn_images/1.json
  def destroy
    @dyn_image.destroy
    respond_to do |format|
      format.html { redirect_to dyn_images_url, notice: 'Dyn image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dyn_image
      @dyn_image = DynImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dyn_image_params
      params.require(:dyn_image).permit(:name, :alttext, :caption, :pagename, :image)
    end
end

app/helpers/dyn_images_helper.rb
module DynImagesHelper
end

app/views/dyn_images/_form.html.erb
<%= form_for @dyn_image, html: { multipart: true } do |f| %>
  <% if dyn_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dyn_image.errors.count, "error") %> prohibited this dyn_image from being saved:</h2>

      <ul>
      <% dyn_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'form-control-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :alttext, class: 'form-control-label' %>
    <%= f.text_field :alttext, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :caption, class: 'form-control-label' %>
    <%= f.text_field :caption, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :image, class: 'form-control-label' %>
    <%= f.file_field :image, class: 'form-control-label' %>
  </div>

  <div class="form-group">
    <%= f.label :pagename, class: 'form-control-label' %>
    <%= f.text_field :pagename, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dyn_images/edit.html.erb
<br>
<h1>Editing Dyn Image</h1>

<%= render 'form', dyn_image: @dyn_image %>

<%= link_to 'Show', @dyn_image %> |
<%= link_to 'Back', dyn_images_path %>

app/views/dyn_images/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<h1>Dynamic Images</h1>

<% DynamicPage.all.each do | dynamicpage| %>
      <div class='btn-group' role='group' aria-label="Page Select">
          <%= link_to dynamicpage.name, images_path(pagename: dynamicpage.name), class: 'btn btn-secondary' %>
      </div>
  <%end%><br>

<table class="table table-striped">
  <thead class="thead thead-default">
    <tr>
      <th>Name</th>
      <th>Alttext</th>
      <th>Caption</th>
      <!--<th>Image</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dyn_images.each do |dyn_image| %>
      <tr>
        <td><%= dyn_image.name %></td>
        <td><%= dyn_image.alttext %></td>
        <td><%= dyn_image.caption %></td>
        <!--<<td> image_tag dyn_image.image.url(:thumb) %></td>-->
        <td><%= link_to 'Show', dyn_image %></td>
        <td><%= link_to 'Edit', edit_dyn_image_path(dyn_image) %></td>
        <td><%= link_to 'Destroy', dyn_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dynamic Image', new_dyn_image_path %>

app/views/dyn_images/new.html.erb
<br>
<h1>New Dynamic Image</h1>

<%= render 'form', dyn_image: @dyn_image %>

<%= link_to 'Back', dyn_images_path %>

app/views/dyn_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dyn_image.name %>
</p>

<p>
  <strong>Alttext:</strong>
  <%= @dyn_image.alttext %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @dyn_image.caption %>
</p>

<!--
<p>
  <strong>Image:</strong>
  %= image_tag @dyn_image.image %>
</p>
-->

<p>
  <strong>Pagename:</strong>
  <%= @dyn_image.pagename %>
</p>
<%= link_to 'Edit', edit_dyn_image_path(@dyn_image) %> |
<%= link_to 'Back', dyn_images_path %>