config/routes.rb
Rails.application.routes.draw do

  resources :dy_contents
  resources :dyn_images
  resources :dynamic_pages
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'membership', to: 'static_pages#membership'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get 'classes', to: 'static_pages#classes'

  get 'contact', to: 'static_pages#contact'
  
  get 'admin', to: 'static_pages#admin'
  
  get 'pages', to: 'dynamic_pages#index'
  
  get 'images', to: 'dyn_images#index'
  
  get 'contents', to: 'dy_contents#index'
  
   root 'static_pages#home'
  
 

  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def membership
  end

  def classes
  end

  def contact
  end
  
  def admin
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/admin.html.erb
<% if logged_in? && current_user.admin? %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Admin Panel</a>
    </div>
    
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="admin_path">Dashboard</a></li>
        <li><a href="#">Settings</a></li>
        <li><a href="#">Profile</a></li>
         <% if logged_in? %>
                  <li><%= link_to "Users", users_path %></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Log out", logout_path, method: "delete" %>
                      </li>
                      </ul>
                    </li>
                  <% else %>
                    <li><%= link_to "Log in", login_path %></li>
                  <% end %>
      </ul>
        
      
    </div>
  </div>
</nav>

<br>
 <hr class="featurette-divider">
<h1>Content Management</h1>


<div class='btn-group' role='group' aria-label="Page Select">
  <%= link_to "Manage Pages", pages_path, class: 'btn btn-secondary' %>
  <%= link_to "Manage Images", images_path, class: 'btn btn-secondary' %>
  <%= link_to "Manage Contents", contents_path, class: 'btn btn-secondary' %>
</div>

<!--
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Reports</a></li>
        <li><a href="#">Analytics</a></li>
        <li><a href="#">Export</a></li>
      </ul>
      
      <ul class="nav nav-sidebar">
        <li><a href="">Nav item</a></li>
        <li><a href="">Nav item again</a></li>
        <li><a href="">One more nav</a></li>
        <li><a href="">Another nav item</a></li>
        <li><a href="">More navigation</a></li>
      </ul>
      
      <ul class="nav nav-sidebar">
        <li><a href="">Nav item again</a></li>
        <li><a href="">One more nav</a></li>
        <li><a href="">Another nav item</a></li>
      </ul>
    </div>
    
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <h1 class="page-header">Dashboard</h1>

      <div class="row placeholders">
        <div class="col-xs-6 col-sm-3 placeholder">
          <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
          <h4>Label</h4>
          <span class="text-muted">Something else</span>
        </div>
        <div class="col-xs-6 col-sm-3 placeholder">
          <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
          <h4>Label</h4>
          <span class="text-muted">Something else</span>
        </div>
        <div class="col-xs-6 col-sm-3 placeholder">
          <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
          <h4>Label</h4>
          <span class="text-muted">Something else</span>
        </div>
        <div class="col-xs-6 col-sm-3 placeholder">
          <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
          <h4>Label</h4>
          <span class="text-muted">Something else</span>
        </div>
      </div>

      <h2 class="sub-header">Section title</h2>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1,001</td>
              <td>Lorem</td>
              <td>ipsum</td>
              <td>dolor</td>
              <td>sit</td>
            </tr>
            <tr>
              <td>1,002</td>
              <td>amet</td>
              <td>consectetur</td>
              <td>adipiscing</td>
              <td>elit</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>Integer</td>
              <td>nec</td>
              <td>odio</td>
              <td>Praesent</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>libero</td>
              <td>Sed</td>
              <td>cursus</td>
              <td>ante</td>
            </tr>
            <tr>
              <td>1,004</td>
              <td>dapibus</td>
              <td>diam</td>
              <td>Sed</td>
              <td>nisi</td>
            </tr>
            <tr>
              <td>1,005</td>
              <td>Nulla</td>
              <td>quis</td>
              <td>sem</td>
              <td>at</td>
            </tr>
            <tr>
              <td>1,006</td>
              <td>nibh</td>
              <td>elementum</td>
              <td>imperdiet</td>
              <td>Duis</td>
            </tr>
            <tr>
              <td>1,007</td>
              <td>sagittis</td>
              <td>ipsum</td>
              <td>Praesent</td>
              <td>mauris</td>
            </tr>
            <tr>
              <td>1,008</td>
              <td>Fusce</td>
              <td>nec</td>
              <td>tellus</td>
              <td>sed</td>
            </tr>
            <tr>
              <td>1,009</td>
              <td>augue</td>
              <td>semper</td>
              <td>porta</td>
              <td>Mauris</td>
            </tr>
            <tr>
              <td>1,010</td>
              <td>massa</td>
              <td>Vestibulum</td>
              <td>lacinia</td>
              <td>arcu</td>
            </tr>
            <tr>
              <td>1,011</td>
              <td>eget</td>
              <td>nulla</td>
              <td>Class</td>
              <td>aptent</td>
            </tr>
            <tr>
              <td>1,012</td>
              <td>taciti</td>
              <td>sociosqu</td>
              <td>ad</td>
              <td>litora</td>
            </tr>
            <tr>
              <td>1,013</td>
              <td>torquent</td>
              <td>per</td>
              <td>conubia</td>
              <td>nostra</td>
            </tr>
            <tr>
              <td>1,014</td>
              <td>per</td>
              <td>inceptos</td>
              <td>himenaeos</td>
              <td>Curabitur</td>
            </tr>
            <tr>
              <td>1,015</td>
              <td>sodales</td>
              <td>ligula</td>
              <td>in</td>
              <td>libero</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>-->
 <hr class="featurette-divider">
 
<%else%>
<p>Sorry this page is only for the Admin</p>
<%end%>

app/views/static_pages/classes.html.erb
 <hr class="featurette-divider">

<div class="container">
   
    <hr>
   
    <div class="row">
        <div class="panel panel-primary filterable">
            <div class="panel-heading">
                <h3 class="panel-title">Available Classes</h3>
                <div class="pull-right">
                    <button class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span> Filter</button>
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr class="filters">
                        <th><input type="text" class="form-control" placeholder="#" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Monday" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Tuesday" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Wednesday" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Thursday" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Friday" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Saturday" disabled></th>
                         <th><input type="text" class="form-control" placeholder="Sunday" disabled></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>10:00AM</td>
                        <td>Spin</td>
                        <td>Dance</td>
                        <td>Yoga</td>
                        <td>Spin</td>
                        <td>Dance</td>
                        <td>Yoga</td>
                        <td>Pilates</td>
                    </tr>
                    <tr>
                        <td>11:00AM</td>
                         <td>Spin</td>
                        <td>Dance</td>
                        <td>Yoga</td>
                        <td>Spin</td>
                        <td>Dance</td>
                        <td>Yoga</td>
                        <td>Pilates</td>
        
                    </tr>
                    <tr>
                        <td>12:00PM</td>
                         <td>Spin</td>
                        <td>Dance</td>
                        <td>Yoga</td>
                        <td>Spin</td>
                        <td>Dance</td>
                        <td>Yoga</td>
                        <td>Pilates</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<hr class="featurette-divider">

app/views/static_pages/contact.html.erb
 <hr class="featurette-divider">

<div class="container" id: 'form'>

  <form class="well form-horizontal" action=" " method="post"  id="contact_form">
  <fieldset>
  <!-- Form Name -->
  <legend><%= (DyContent.find_by description: 'Form_Legend').content %></legend>
  
  <!-- Text input-->
  
  <div class="form-group">
    <label class="col-md-4 control-label">First Name</label>  
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
    <input  name="first_name" placeholder="First Name" class="form-control"  type="text">
      </div>
    </div>
  </div>

  <!-- Text input-->
  
  <div class="form-group">
    <label class="col-md-4 control-label" >Last Name</label> 
      <div class="col-md-4 inputGroupContainer">
      <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
    <input name="last_name" placeholder="Last Name" class="form-control"  type="text">
      </div>
    </div>
  </div>
  
  <!-- Text input-->
  <div class="form-group">
    <label class="col-md-4 control-label">E-Mail</label>  
      <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
          <input name="email" placeholder="E-Mail Address" class="form-control"  type="text">
      </div>
    </div>
  </div>
  
  
  <!-- Text input-->
         
  <div class="form-group">
    <label class="col-md-4 control-label">Phone #</label>  
      <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
          <input name="phone" placeholder="(845)555-1212" class="form-control" type="text">
      </div>
    </div>
  </div>
  
  <!-- Text area -->
    
  <div class="form-group">
    <label class="col-md-4 control-label">Project Description</label>
      <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
          <textarea class="form-control" name="comment" placeholder="Project Description"></textarea>
      </div>
    </div>
  </div>
  
  <!-- Success message -->
  <div class="alert alert-success" role="alert" id="success_message">Success <i class="glyphicon glyphicon-thumbs-up"></i> Thanks for contacting us, we will get back to you shortly.</div>
  
  <!-- Button -->
  <div class="form-group">
    <label class="col-md-4 control-label"></label>
      <div class="col-md-4">
        <button type="submit" class="btn btn-warning" >Send <span class="glyphicon glyphicon-send"></span></button>
    </div>
  </div>
  </fieldset>
  </form>
  
  <div>
    <div class="form-group">
      <h3 class="form-group"><%= (DyContent.find_by description: 'Address_Header').content %></h3>
      <address class="form-group">
        <%= (DyContent.find_by description: 'Address_Street').content %><br>
        <%= (DyContent.find_by description: 'Address_Extension').content %><br>
        <%= (DyContent.find_by description: 'Address_City').content %><br>
        <%= (DyContent.find_by description: 'Address_Eircode').content %><br>
      </address>
    </div>
  </div>
 
  <div>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2382.6973467719563!2d-6.279901054405767!3d53.33077211777081!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48670c1833b915c7%3A0x4f83acae16f5062e!2sGriffith+College!5e0!3m2!1sen!2sie!4v1493200106714" class="fill" frameborder="0" style="border:0" allowfullscreen></iframe>    
  </div>  
 
  </div>
</div><!-- /.container -->

 <hr class="featurette-divider">

app/views/static_pages/home.html.erb
<div class="carousel slide" data-ride="carousel" id="my-carousel">
  <!-- indicators -->
  <ol class="carousel-indicators">
    <li data-target="#my-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#my-carousel" data-slide-to="1"></li>
    <li data-target="#my-carousel" data-slide-to="2"></li>
  </ol>
  
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
     <%= link_to image_tag((DynImage.find_by name: 'Slider_Image1').image, alt: (DynImage.find_by name: 'Slider_Image1').alttext)%>
     <div class="container">
            <div class="carousel-caption">
              <h1><%= (DyContent.find_by description: 'Slider_Header0').content %></h1>
              <p><%= (DyContent.find_by description: 'Slider_Paragraph0').content %></p>
              <%= link_to "Sign up now!", 'membership', class: "btn btn-lg btn-primary" %>
            </div>
          </div>
    </div>
    
    <div class="item">
      <%= link_to image_tag("img5.jpg", alt: "slide 2")%>
      <div class="container">
            <div class="carousel-caption">
              <h1><%= (DyContent.find_by description: 'Slider_Header1').content %></h1>
              <p><%= (DyContent.find_by description: 'Slider_Paragraph1').content %></p>
               <%= link_to "Learn More", 'contact', class: "btn btn-lg btn-primary" %>
            </div>
    </div>
    </div>
    <div class="item">
     <%= link_to image_tag("img5.jpg")%>
     <div class="container">
            <div class="carousel-caption">
              <h1><%= (DyContent.find_by description: 'Slider_Header2').content %></h1>
              <p><%= (DyContent.find_by description: 'Slider_Paragraph2').content %></p>
               <%= link_to "View Classes", 'classes', class: "btn btn-lg btn-primary" %>
            </div>
          </div>
      </div>
    </div>
    
  <!-- Controls -->
  <a class="left carousel-control" href="#my-carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#my-carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
</div>


 <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container">
      
      <hr class="featurette-divider">
      
      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading"><%= (DyContent.find_by description: 'Feat1_Heading_Part1').content %> <span class="text-muted"><%= (DyContent.find_by description: 'Feat1_Heading_Part2').content %></span></h2>
          <p class="lead"><%= (DyContent.find_by description: 'Feat1_content').content %></p>
        </div>
        <div class="col-md-5">
            <%= link_to image_tag("mem1.jpg", alt: "logo", class: "featurette-image img-responsive center-block")%>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading"><%= (DyContent.find_by description: 'Feat2_Heading_Part2').content %> <span class="text-muted"><%= (DyContent.find_by description: 'Feat2_Heading_Part1').content %></span></h2>
          <p class="lead"><%= (DyContent.find_by description: 'Feat2_content').content %></p>
        </div>
        <div class="col-md-5 col-md-pull-7">
          <%= link_to image_tag("img4.jpg", alt: "logo", class: "featurette-image img-responsive center-block")%>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading"><%= (DyContent.find_by description: 'Feat3_Heading_Part1').content %> <span class="text-muted"><%= (DyContent.find_by description: 'Feat3_Heading_Part2').content %></span></h2>
          <p class="lead"><%= (DyContent.find_by description: 'Feat3_content').content %> </p>
        </div>
        <div class="col-md-5">
          <%= link_to image_tag("img7.jpg", alt: "logo", class: "featurette-image img-responsive center-block")%>
        </div>
      </div>

      <hr class="featurette-divider">
      
      </div>

      <!-- /END THE FEATURETTES -->
      
      

app/views/static_pages/membership.html.erb
<!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container">
      
      <hr class="featurette-divider">
      
      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading"><%= (DyContent.find_by description: 'Membership_Feat1_part1').content %> <span class="text-muted"><%= (DyContent.find_by description: 'Membership_Feat1_part2').content %></span></h2>
          <p class="lead"><span class="glyphicon glyphicon-ok" aria-hidden="true">&nbsp<%= (DyContent.find_by description: 'Membership_Feat1_row1').content %></p></span>
          <p class="lead"><span class="glyphicon glyphicon-ok" aria-hidden="true">&nbsp<%= (DyContent.find_by description: 'Membership_Feat1_row2').content %></p></span>
          <p class="lead"><span class="glyphicon glyphicon-ok" aria-hidden="true">&nbsp<%= (DyContent.find_by description: 'Membership_Feat1_row3').content %> </p></span>
           <%= link_to "Learn More", 'contact', class: "btn btn-lg btn-primary" %>
        </div>
        <div class="col-md-5">
            <%= link_to image_tag("mem1.jpg", alt: "logo", class: "featurette-image img-responsive center-block")%>
  
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading"><%= (DyContent.find_by description: 'Membership_Feat2_header').content %></h2>
          <p class="lead"><%= (DyContent.find_by description: 'Membership_Feat2_paragraph').content %></p>
           <p class="lead"><span class="glyphicon glyphicon-ok" aria-hidden="true">&nbsp<%= (DyContent.find_by description: 'Membership_Feat2_row1').content %></p></span>
            <p class="lead"><span class="glyphicon glyphicon-ok" aria-hidden="true">&nbsp<%= (DyContent.find_by description: 'Membership_Feat2_row2').content %></p></span>
            <p class="lead"><span class="glyphicon glyphicon-ok" aria-hidden="true">&nbsp<%= (DyContent.find_by description: 'Membership_Feat2_row3').content %></p></span>
        </div>
        <div class="col-md-5 col-md-pull-7">
          <%= link_to image_tag("img9.jpg", alt: "logo", class: "featurette-image img-responsive center-block")%>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading"><%= (DyContent.find_by description: 'Membership_Feat3_header').content %></h2>
          <p class="lead"><%= (DyContent.find_by description: 'Membership_Feat3_paragraph').content %></p>
          <p class="lead"><%= (DyContent.find_by description: 'Membership_Feat3_paragraph2').content %></p>
          <p class="lead"><%= (DyContent.find_by description: 'Membership_Feat3_paragraph3').content %></p>
        </div>
        <div class="col-md-5">
          <%= link_to image_tag("img7.jpg", alt: "logo", class: "featurette-image img-responsive center-block")%>
        </div>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->
    
      