config/routes.rb
Rails.application.routes.draw do

  resources :dy_contents
  resources :dyn_images
  resources :dynamic_pages
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'membership', to: 'static_pages#membership'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get 'classes', to: 'static_pages#classes'

  get 'contact', to: 'static_pages#contact'
  
  get 'admin', to: 'static_pages#admin'
  
  get 'pages', to: 'dynamic_pages#index'
  
  get 'images', to: 'dyn_images#index'
  
  get 'contents', to: 'dy_contents#index'
  
   root 'static_pages#home'
  
 

  
end

app/models/dynamic_page.rb
class DynamicPage < ApplicationRecord
    validates :name, :title, :pagetype, presence: true 
end

app/controllers/dynamic_pages_controller.rb
class DynamicPagesController < ApplicationController
  before_action :set_dynamic_page, only: [:show, :edit, :update, :destroy]

  # GET /dynamic_pages
  # GET /dynamic_pages.json
  def index
    @dynamic_pages = DynamicPage.all
  end

  # GET /dynamic_pages/1
  # GET /dynamic_pages/1.json
  def show
  end

  # GET /dynamic_pages/new
  def new
    @dynamic_page = DynamicPage.new
  end

  # GET /dynamic_pages/1/edit
  def edit
  end

  # POST /dynamic_pages
  # POST /dynamic_pages.json
  def create
    @dynamic_page = DynamicPage.new(dynamic_page_params)

    respond_to do |format|
      if @dynamic_page.save
        format.html { redirect_to @dynamic_page, notice: 'Dynamic page was successfully created.' }
        format.json { render :show, status: :created, location: @dynamic_page }
      else
        format.html { render :new }
        format.json { render json: @dynamic_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dynamic_pages/1
  # PATCH/PUT /dynamic_pages/1.json
  def update
    respond_to do |format|
      if @dynamic_page.update(dynamic_page_params)
        format.html { redirect_to @dynamic_page, notice: 'Dynamic page was successfully updated.' }
        format.json { render :show, status: :ok, location: @dynamic_page }
      else
        format.html { render :edit }
        format.json { render json: @dynamic_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dynamic_pages/1
  # DELETE /dynamic_pages/1.json
  def destroy
    @dynamic_page.destroy
    respond_to do |format|
      format.html { redirect_to dynamic_pages_url, notice: 'Dynamic page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dynamic_page
      @dynamic_page = DynamicPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dynamic_page_params
      params.require(:dynamic_page).permit(:name, :title, :pagetype)
    end
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/views/dynamic_pages/_form.html.erb
<%= form_for(dynamic_page) do |f| %>
  <% if dynamic_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dynamic_page.errors.count, "error") %> prohibited this dynamic_page from being saved:</h2>

      <ul>
      <% dynamic_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'form-control-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :title, class: 'form-control-label'%>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pagetype, class: 'form-control-label' %>
    <%= f.text_field :pagetype, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dynamic_pages/edit.html.erb
<br>
<h1>Editing Dynamic Page</h1>

<%= render 'form', dynamic_page: @dynamic_page %>

<%= link_to 'Show', @dynamic_page %> |
<%= link_to 'Back', dynamic_pages_path %>

app/views/dynamic_pages/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<h1>Dynamic Pages</h1>

<table class="table table-striped">
  <thead class="thead thead-default">
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Pagetype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dynamic_pages.each do |dynamic_page| %>
      <tr>
        <td><%= dynamic_page.name %></td>
        <td><%= dynamic_page.title %></td>
        <td><%= dynamic_page.pagetype %></td>
        <td><%= link_to 'Show', dynamic_page %></td>
        <td><%= link_to 'Edit', edit_dynamic_page_path(dynamic_page) %></td>
        <% if !dynamic_page.pagetype == "default" %> 
          <td><%= link_to 'Destroy', dynamic_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dynamic Page', new_dynamic_page_path, class: 'btn btn-secondary' %>

app/views/dynamic_pages/new.html.erb
<br>
<h1>New Dynamic Page</h1>

<%= render 'form', dynamic_page: @dynamic_page %>

<%= link_to 'Back', dynamic_pages_path %>

app/views/dynamic_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dynamic_page.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @dynamic_page.title %>
</p>

<p>
  <strong>Pagetype:</strong>
  <%= @dynamic_page.pagetype %>
</p>

<%= link_to 'Edit', edit_dynamic_page_path(@dynamic_page) %> |
<%= link_to 'Back', dynamic_pages_path %>